# https://jekyllrb.com/docs/step-by-step/09-collections/
collections:
  aulas:
    output: true

markdown: kramdown
permalink: pretty
url: https://infosimples.github.io
base_url: /estagio-em-programacao

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
